# Лабораторная работа 3

**Решение уравнения**

In [1]:
import numpy as np


def learn(scheme, epochs, X, Y, L):
    inputLayerSize, hiddenLayerSize, outputLayerSize = scheme

    def sigmoid(x): return 1 / (1 + np.exp(-x))  # activation function

    def sigmoid_(x): return x * (1 - x)  # derivative of sigmoid

    # weights on layer inputs
    Wh = np.random.uniform(size=(inputLayerSize, hiddenLayerSize))
    Wz = np.random.uniform(size=(hiddenLayerSize, outputLayerSize))

    for _ in range(epochs):
        H = sigmoid(np.dot(X, Wh))  # hidden layer results
        Z = np.dot(H, Wz)  # output layer, no activation
        E = Y - Z  # error
        dZ = E * L  # delta Z
        Wz += H.T.dot(dZ)  # update output layer weights
        dH = dZ.dot(Wz.T) * sigmoid_(H)  # delta H
        Wh += X.T.dot(dH)  # update hidden layer weights

    print('Hidden layer: \n' + str(Wh))
    print('Output layer: \n' + str(Wz))

    print('Z: \n' + str(Z))




def gen_data():
    x = np.arange(0.1, 5, 0.1)
    x = x.reshape(x.size, 1)
    C = 0.9 * np.random.rand() + 0.1
    A = 0.9 * np.random.rand() + 0.1
    S = 0.9 * np.random.rand() + 0.1
    print('\nC = ' + str(C) + '\nA = ' + str(A) + '\nS = ' + str(S))

    # return C * np.exp(-(np.power((x - A), 2) / S)), np.array(encl([C,A,S],x.size))
    return C * np.exp(-(np.power((x - A), 2) / S)), np.array([C,A,S])

#
# def den_m():
#     P = np.zeros([100, 21])
#     T = np.zeros([3, 100])
#     x = np.arange(0.1, 5*np.exp(-2), 1)
#     for _ in range(0, 100):
#         c = 0.9 * np.random.rand() + 0.1
#         a = 0.9 * np.random.rand() + 0.1
#         s = 0.9 * np.random.rand() + 0.1
#         T[0, _] = c
#         T[1, _] = a
#         T[2, _] = s
#         P[_,:] =c * np.exp(-(np.power((x - a),2) / s))
#
#     return P,T

def encl(l ,n):
    s = []
    for i in range(0,n):
        s.append(l)
    return s

data = gen_data()
np.seterrcall(learn([1, 15, 3], 2000, data[0].reshape(data[0].size, 1), data[1].T, 0.01))


C = 0.2619743420816263
A = 0.2056745003123574
S = 0.5225682420945922
Hidden layer: 
[[0.77520227 0.74838915 0.93444378 0.21807929 0.98498512 0.37889927
  0.30650433 0.71719501 0.92806809 0.13402979 0.88992582 0.94104518
  0.51111585 0.27843519 1.00164771]]
Output layer: 
[[-0.0592591   0.45013548 -0.36227508]
 [ 0.40354257 -0.15041222  0.50671834]
 [ 0.09671553 -0.00715043 -0.16536905]
 [ 0.11514637 -0.15202744  0.11111383]
 [-0.37463108  0.49100964 -0.28181253]
 [ 0.24102425  0.02764947  0.07197269]
 [ 0.13705471 -0.109981    0.50235964]
 [ 0.41701398 -0.07627371 -0.14086015]
 [-0.02220173 -0.16085786  0.34870698]
 [ 0.47175376  0.38509649  0.47052634]
 [-0.23187738  0.38628525 -0.37138206]
 [-0.40320698 -0.33364039 -0.22678645]
 [-0.34075932 -0.07322474  0.55822937]
 [-0.37745893  0.13036224 -0.30404223]
 [ 0.44968097 -0.39860605  0.32490913]]
Z: 
[[0.26533625 0.21276044 0.530018  ]
 [0.26542514 0.2129446  0.53021475]
 [0.26535421 0.21279766 0.53005775]
 [0.26513176 0.21233599 0.529